server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
    datasource:
        name: bysj
        url: jdbc:mysql://10.0.0.83:3306/bysj
        username: root
        password: sneakerhead
    mvc:
        view:
          prefix: /WEB-INF/back_page/
          suffix: .jsp
    devtools:
      restart:
        enabled: true
        exclude: WEB-INF/**
        additional-paths: src/main
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bysj
logging:
    file:   # 日志文件,绝对路径或相对路径
    path:   # 保存日志文件目录路径
    config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
    level:  # 日志级别
#        org.springframework.web: debug # 配置spring web日志级别
        cn.bysj : debug

